global:
    debug: 1
    verbose: 1

    tempdir: "/tmp"

    persistence: True
    virtualization: True

resources:
    language: fr

    alphabet: /home/resources/media/fr/unitex/preprocessing/Alphabet.txt
    alphabet-sorted: /home/resources/media/fr/unitex/preprocessing/Alphabet_sort.txt
    sentence: /home/resources/media/fr/unitex/preprocessing/sentence/Sentence.fst2
    replace: /home/resources/media/fr/unitex/preprocessing/replace/Replace.fst2

    dictionaries:
        - /home/resources/media/fr/unitex/dictionary/delaf-short.bin
        - /home/resources/media/fr/unitex/dictionary/delacf-light.bin
        - /home/resources/media/fr/unitex/dictionary/toponyms.bin

# The 'options' section can contain any of the argument used by the unitex tools
# functions. Note that some argument will be overriden to fit the 'tag' and 'extract'
# behaviour. For intance, there is not point to define a font or a context for
# 'concord'.
options:
    locate:
        match_mode: longest
